# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-28 05:46
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=75)),
                ('last_name', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message=b"Phone number must be entered in the format: '+16045555555'.", regex=b'^\\+?1?\\d{10,12}$')])),
                ('address_line1', models.CharField(blank=True, max_length=50, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('province', models.CharField(blank=True, choices=[(b'AB', b'Alberta'), (b'BC', b'British Columbia'), (b'ON', b'Ontario'), (b'NS', b'Nova Scotia'), (b'NL', b'Newfoundland and Labrador'), (b'NU', b'Nunavut'), (b'YT', b'Yukon'), (b'MB', b'Manitoba'), (b'SK', b'Saskatchewan'), (b'PE', b'Prince Edward Island'), (b'NT', b'Northwest Territories'), (b'NB', b'New Brunswick'), (b'QC', b'Quebec')], max_length=20, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=50, verbose_name=b'Organization Name')),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('year_donation', models.IntegerField(blank=True, null=True, verbose_name=b'Year')),
                ('amount_donation', models.IntegerField(blank=True, null=True, verbose_name=b'Amount Donated')),
                ('primary_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='donor1', to='vjk.Contact')),
                ('secondary_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='donor2', to='vjk.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('service_provided', models.CharField(blank=True, max_length=50, null=True)),
                ('primary_contact', models.ForeignKey(blank=True, default=-1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sponsor1', to='vjk.Contact')),
                ('secondary_contact', models.ForeignKey(blank=True, default=-1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sponsor2', to='vjk.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=75)),
                ('last_name', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=254)),
                ('school', models.CharField(blank=True, max_length=75, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message=b"Phone number must be entered in the format: '+16045555555'.", regex=b'^\\+?1?\\d{10,12}$')])),
                ('program_city', models.CharField(blank=True, max_length=100, null=True)),
                ('year_attended', models.IntegerField(blank=True, null=True)),
                ('program_institution', models.CharField(blank=True, max_length=75, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=50, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('province', models.CharField(blank=True, choices=[(b'AB', b'Alberta'), (b'BC', b'British Columbia'), (b'ON', b'Ontario'), (b'NS', b'Nova Scotia'), (b'NL', b'Newfoundland and Labrador'), (b'NU', b'Nunavut'), (b'YT', b'Yukon'), (b'MB', b'Manitoba'), (b'SK', b'Saskatchewan'), (b'PE', b'Prince Edward Island'), (b'NT', b'Northwest Territories'), (b'NB', b'New Brunswick'), (b'QC', b'Quebec')], max_length=20, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=6, null=True)),
                ('reference_fname', models.CharField(default=b'', max_length=75, verbose_name=b'Reference First Name')),
                ('reference_lname', models.CharField(default=b'', max_length=75, verbose_name=b'Reference Last Name')),
                ('reference_email', models.EmailField(default=b'', max_length=254, verbose_name=b'Reference Email')),
                ('reference_number', models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message=b"Phone number must be entered in the format: '+16045555555'.", regex=b'^\\+?1?\\d{10,12}$')])),
                ('reference_address_line1', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_address_line2', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_city', models.CharField(blank=True, max_length=30, null=True)),
                ('reference_province', models.CharField(blank=True, choices=[(b'AB', b'Alberta'), (b'BC', b'British Columbia'), (b'ON', b'Ontario'), (b'NS', b'Nova Scotia'), (b'NL', b'Newfoundland and Labrador'), (b'NU', b'Nunavut'), (b'YT', b'Yukon'), (b'MB', b'Manitoba'), (b'SK', b'Saskatchewan'), (b'PE', b'Prince Edward Island'), (b'NT', b'Northwest Territories'), (b'NB', b'New Brunswick'), (b'QC', b'Quebec')], max_length=20, null=True)),
                ('reference_postal_code', models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=75)),
                ('last_name', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message=b"Phone number must be entered in the format: '+16045555555'.", regex=b'^\\+?1?\\d{10,12}$')])),
                ('address_line1', models.CharField(blank=True, max_length=50, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('province', models.CharField(blank=True, choices=[(b'AB', b'Alberta'), (b'BC', b'British Columbia'), (b'ON', b'Ontario'), (b'NS', b'Nova Scotia'), (b'NL', b'Newfoundland and Labrador'), (b'NU', b'Nunavut'), (b'YT', b'Yukon'), (b'MB', b'Manitoba'), (b'SK', b'Saskatchewan'), (b'PE', b'Prince Edward Island'), (b'NT', b'Northwest Territories'), (b'NB', b'New Brunswick'), (b'QC', b'Quebec')], max_length=20, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=6, null=True)),
                ('role', models.CharField(blank=True, max_length=75, null=True)),
                ('years_helped', models.CharField(blank=True, default=b'', max_length=75, null=True)),
            ],
        ),
    ]
