# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=75)),
                ('last_name', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('donor', models.BooleanField()),
                ('sponsor', models.BooleanField()),
                ('student', models.BooleanField()),
                ('volunteer', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Donors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('year_donation', models.IntegerField()),
                ('amount_donation', models.IntegerField()),
                ('primary_contact', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='vjk.Contacts')),
                ('secondary_contact', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='vjk.Contacts')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('service_provided', models.CharField(max_length=50)),
                ('primary_contact', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='vjk.Contacts')),
                ('secondary_contact', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='vjk.Contacts')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=75)),
                ('last_name', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=75)),
                ('year_attended', models.IntegerField()),
                ('reference_fname', models.CharField(default=b'', max_length=75)),
                ('reference_lname', models.CharField(default=b'', max_length=75)),
                ('reference_email', models.EmailField(default=b'', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=75)),
                ('last_name', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=75)),
                ('years_helped', models.CharField(default=b'', max_length=75)),
            ],
        ),
    ]
