# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vjk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsors',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
