# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-09 05:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vjk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='province',
            field=models.CharField(blank=True, choices=[('NL', 'Newfoundland and Labrador'), ('AB', 'Alberta'), ('YT', 'Yukon'), ('NT', 'Northwest Territories'), ('ON', 'Ontario'), ('QC', 'Quebec'), ('PE', 'Prince Edward Island'), ('SK', 'Saskatchewan'), ('BC', 'British Columbia'), ('NS', 'Nova Scotia'), ('NB', 'New Brunswick'), ('MB', 'Manitoba'), ('NU', 'Nunavut')], max_length=20, null=True, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='secondary_contact',
            field=models.ForeignKey(blank=True, default=-1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sponsor2', to='vjk.Contact', verbose_name='Secondary Contact'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='service_provided',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Service Provided'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+16045555555'.", regex='^\\+?1?\\d{10,12}$')], verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='student',
            name='province',
            field=models.CharField(blank=True, choices=[('NL', 'Newfoundland and Labrador'), ('AB', 'Alberta'), ('YT', 'Yukon'), ('NT', 'Northwest Territories'), ('ON', 'Ontario'), ('QC', 'Quebec'), ('PE', 'Prince Edward Island'), ('SK', 'Saskatchewan'), ('BC', 'British Columbia'), ('NS', 'Nova Scotia'), ('NB', 'New Brunswick'), ('MB', 'Manitoba'), ('NU', 'Nunavut')], max_length=20, null=True, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='student',
            name='reference_email',
            field=models.EmailField(default='', max_length=254, verbose_name='Ref. E-mail'),
        ),
        migrations.AlterField(
            model_name='student',
            name='reference_province',
            field=models.CharField(blank=True, choices=[('NL', 'Newfoundland and Labrador'), ('AB', 'Alberta'), ('YT', 'Yukon'), ('NT', 'Northwest Territories'), ('ON', 'Ontario'), ('QC', 'Quebec'), ('PE', 'Prince Edward Island'), ('SK', 'Saskatchewan'), ('BC', 'British Columbia'), ('NS', 'Nova Scotia'), ('NB', 'New Brunswick'), ('MB', 'Manitoba'), ('NU', 'Nunavut')], max_length=20, null=True, verbose_name='Ref. Province'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='province',
            field=models.CharField(blank=True, choices=[('NL', 'Newfoundland and Labrador'), ('AB', 'Alberta'), ('YT', 'Yukon'), ('NT', 'Northwest Territories'), ('ON', 'Ontario'), ('QC', 'Quebec'), ('PE', 'Prince Edward Island'), ('SK', 'Saskatchewan'), ('BC', 'British Columbia'), ('NS', 'Nova Scotia'), ('NB', 'New Brunswick'), ('MB', 'Manitoba'), ('NU', 'Nunavut')], max_length=20, null=True, verbose_name='Province'),
        ),
    ]
