# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-07 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vjk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='primary_contact',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='secondary_contact',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='primary_contact',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='secondary_contact',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Volunteer',
        ),
        migrations.DeleteModel(
            name='Donor',
        ),
        migrations.DeleteModel(
            name='Sponsor',
        ),
    ]
