# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-01 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vjk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='province',
            field=models.CharField(blank=True, choices=[('MB', 'Manitoba'), ('ON', 'Ontario'), ('NU', 'Nunavut'), ('QC', 'Quebec'), ('BC', 'British Columbia'), ('NS', 'Nova Scotia'), ('NL', 'Newfoundland and Labrador'), ('NT', 'Northwest Territories'), ('PE', 'Prince Edward Island'), ('SK', 'Saskatchewan'), ('YT', 'Yukon'), ('AB', 'Alberta'), ('NB', 'New Brunswick')], max_length=20, null=True, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='student',
            name='province',
            field=models.CharField(blank=True, choices=[('MB', 'Manitoba'), ('ON', 'Ontario'), ('NU', 'Nunavut'), ('QC', 'Quebec'), ('BC', 'British Columbia'), ('NS', 'Nova Scotia'), ('NL', 'Newfoundland and Labrador'), ('NT', 'Northwest Territories'), ('PE', 'Prince Edward Island'), ('SK', 'Saskatchewan'), ('YT', 'Yukon'), ('AB', 'Alberta'), ('NB', 'New Brunswick')], max_length=20, null=True, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='student',
            name='reference_province',
            field=models.CharField(blank=True, choices=[('MB', 'Manitoba'), ('ON', 'Ontario'), ('NU', 'Nunavut'), ('QC', 'Quebec'), ('BC', 'British Columbia'), ('NS', 'Nova Scotia'), ('NL', 'Newfoundland and Labrador'), ('NT', 'Northwest Territories'), ('PE', 'Prince Edward Island'), ('SK', 'Saskatchewan'), ('YT', 'Yukon'), ('AB', 'Alberta'), ('NB', 'New Brunswick')], max_length=20, null=True, verbose_name='Ref. Province'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='province',
            field=models.CharField(blank=True, choices=[('MB', 'Manitoba'), ('ON', 'Ontario'), ('NU', 'Nunavut'), ('QC', 'Quebec'), ('BC', 'British Columbia'), ('NS', 'Nova Scotia'), ('NL', 'Newfoundland and Labrador'), ('NT', 'Northwest Territories'), ('PE', 'Prince Edward Island'), ('SK', 'Saskatchewan'), ('YT', 'Yukon'), ('AB', 'Alberta'), ('NB', 'New Brunswick')], max_length=20, null=True, verbose_name='Province'),
        ),
    ]
