# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-07 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vjk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='reference_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='students',
            name='reference_fname',
            field=models.CharField(default='', max_length=75),
        ),
        migrations.AlterField(
            model_name='students',
            name='reference_lname',
            field=models.CharField(default='', max_length=75),
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='years_helped',
            field=models.CharField(default='', max_length=75),
        ),
    ]
