# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-01 20:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vjk', '0002_auto_20170701_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='province',
            field=models.CharField(blank=True, choices=[('NL', 'Newfoundland and Labrador'), ('NT', 'Northwest Territories'), ('NS', 'Nova Scotia'), ('NU', 'Nunavut'), ('AB', 'Alberta'), ('SK', 'Saskatchewan'), ('YT', 'Yukon'), ('NB', 'New Brunswick'), ('QC', 'Quebec'), ('BC', 'British Columbia'), ('ON', 'Ontario'), ('MB', 'Manitoba'), ('PE', 'Prince Edward Island')], max_length=20, null=True, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='secondary_contact',
            field=models.ForeignKey(blank=True, default=-1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sponsor2', to='vjk.Contact', verbose_name='Secondary Contact'),
        ),
        migrations.AlterField(
            model_name='student',
            name='province',
            field=models.CharField(blank=True, choices=[('NL', 'Newfoundland and Labrador'), ('NT', 'Northwest Territories'), ('NS', 'Nova Scotia'), ('NU', 'Nunavut'), ('AB', 'Alberta'), ('SK', 'Saskatchewan'), ('YT', 'Yukon'), ('NB', 'New Brunswick'), ('QC', 'Quebec'), ('BC', 'British Columbia'), ('ON', 'Ontario'), ('MB', 'Manitoba'), ('PE', 'Prince Edward Island')], max_length=20, null=True, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='student',
            name='reference_province',
            field=models.CharField(blank=True, choices=[('NL', 'Newfoundland and Labrador'), ('NT', 'Northwest Territories'), ('NS', 'Nova Scotia'), ('NU', 'Nunavut'), ('AB', 'Alberta'), ('SK', 'Saskatchewan'), ('YT', 'Yukon'), ('NB', 'New Brunswick'), ('QC', 'Quebec'), ('BC', 'British Columbia'), ('ON', 'Ontario'), ('MB', 'Manitoba'), ('PE', 'Prince Edward Island')], max_length=20, null=True, verbose_name='Ref. Province'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='province',
            field=models.CharField(blank=True, choices=[('NL', 'Newfoundland and Labrador'), ('NT', 'Northwest Territories'), ('NS', 'Nova Scotia'), ('NU', 'Nunavut'), ('AB', 'Alberta'), ('SK', 'Saskatchewan'), ('YT', 'Yukon'), ('NB', 'New Brunswick'), ('QC', 'Quebec'), ('BC', 'British Columbia'), ('ON', 'Ontario'), ('MB', 'Manitoba'), ('PE', 'Prince Edward Island')], max_length=20, null=True, verbose_name='Province'),
        ),
    ]
