# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 04:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vjk', '0002_auto_20170329_1638'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sponsors',
        ),
    ]
