# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-09 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vjk', '0002_auto_20170708_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='province',
            field=models.CharField(blank=True, choices=[('NT', 'Northwest Territories'), ('NL', 'Newfoundland and Labrador'), ('NB', 'New Brunswick'), ('QC', 'Quebec'), ('NS', 'Nova Scotia'), ('BC', 'British Columbia'), ('AB', 'Alberta'), ('MB', 'Manitoba'), ('YT', 'Yukon'), ('NU', 'Nunavut'), ('ON', 'Ontario'), ('PE', 'Prince Edward Island'), ('SK', 'Saskatchewan')], max_length=20, null=True, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='student',
            name='province',
            field=models.CharField(blank=True, choices=[('NT', 'Northwest Territories'), ('NL', 'Newfoundland and Labrador'), ('NB', 'New Brunswick'), ('QC', 'Quebec'), ('NS', 'Nova Scotia'), ('BC', 'British Columbia'), ('AB', 'Alberta'), ('MB', 'Manitoba'), ('YT', 'Yukon'), ('NU', 'Nunavut'), ('ON', 'Ontario'), ('PE', 'Prince Edward Island'), ('SK', 'Saskatchewan')], max_length=20, null=True, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='student',
            name='reference_province',
            field=models.CharField(blank=True, choices=[('NT', 'Northwest Territories'), ('NL', 'Newfoundland and Labrador'), ('NB', 'New Brunswick'), ('QC', 'Quebec'), ('NS', 'Nova Scotia'), ('BC', 'British Columbia'), ('AB', 'Alberta'), ('MB', 'Manitoba'), ('YT', 'Yukon'), ('NU', 'Nunavut'), ('ON', 'Ontario'), ('PE', 'Prince Edward Island'), ('SK', 'Saskatchewan')], max_length=20, null=True, verbose_name='Ref. Province'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='province',
            field=models.CharField(blank=True, choices=[('NT', 'Northwest Territories'), ('NL', 'Newfoundland and Labrador'), ('NB', 'New Brunswick'), ('QC', 'Quebec'), ('NS', 'Nova Scotia'), ('BC', 'British Columbia'), ('AB', 'Alberta'), ('MB', 'Manitoba'), ('YT', 'Yukon'), ('NU', 'Nunavut'), ('ON', 'Ontario'), ('PE', 'Prince Edward Island'), ('SK', 'Saskatchewan')], max_length=20, null=True, verbose_name='Province'),
        ),
    ]
