# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-07 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vjk', '0002_auto_20170507_0818'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
        migrations.RenameModel(
            old_name='Donors',
            new_name='Donor',
        ),
        migrations.RenameModel(
            old_name='Sponsors',
            new_name='Sponsor',
        ),
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
        migrations.RenameModel(
            old_name='Volunteers',
            new_name='Volunteer',
        ),
    ]
