# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-07 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vjk', '0002_auto_20170507_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('year_donation', models.IntegerField()),
                ('amount_donation', models.IntegerField()),
                ('primary_contact', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='vjk.Contact')),
                ('secondary_contact', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='vjk.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('service_provided', models.CharField(max_length=50)),
                ('primary_contact', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='vjk.Contact')),
                ('secondary_contact', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='vjk.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=75)),
                ('last_name', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=75)),
                ('year_attended', models.IntegerField()),
                ('reference_fname', models.CharField(default='', max_length=75)),
                ('reference_lname', models.CharField(default='', max_length=75)),
                ('reference_email', models.EmailField(default='', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=75)),
                ('last_name', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=75)),
                ('years_helped', models.CharField(default='', max_length=75)),
            ],
        ),
    ]
