# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-03 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vjk', '0003_auto_20170701_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='province',
            field=models.CharField(blank=True, choices=[('AB', 'Alberta'), ('BC', 'British Columbia'), ('NB', 'New Brunswick'), ('NS', 'Nova Scotia'), ('NU', 'Nunavut'), ('MB', 'Manitoba'), ('QC', 'Quebec'), ('YT', 'Yukon'), ('PE', 'Prince Edward Island'), ('NT', 'Northwest Territories'), ('SK', 'Saskatchewan'), ('NL', 'Newfoundland and Labrador'), ('ON', 'Ontario')], max_length=20, null=True, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='student',
            name='province',
            field=models.CharField(blank=True, choices=[('AB', 'Alberta'), ('BC', 'British Columbia'), ('NB', 'New Brunswick'), ('NS', 'Nova Scotia'), ('NU', 'Nunavut'), ('MB', 'Manitoba'), ('QC', 'Quebec'), ('YT', 'Yukon'), ('PE', 'Prince Edward Island'), ('NT', 'Northwest Territories'), ('SK', 'Saskatchewan'), ('NL', 'Newfoundland and Labrador'), ('ON', 'Ontario')], max_length=20, null=True, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='student',
            name='reference_province',
            field=models.CharField(blank=True, choices=[('AB', 'Alberta'), ('BC', 'British Columbia'), ('NB', 'New Brunswick'), ('NS', 'Nova Scotia'), ('NU', 'Nunavut'), ('MB', 'Manitoba'), ('QC', 'Quebec'), ('YT', 'Yukon'), ('PE', 'Prince Edward Island'), ('NT', 'Northwest Territories'), ('SK', 'Saskatchewan'), ('NL', 'Newfoundland and Labrador'), ('ON', 'Ontario')], max_length=20, null=True, verbose_name='Ref. Province'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='province',
            field=models.CharField(blank=True, choices=[('AB', 'Alberta'), ('BC', 'British Columbia'), ('NB', 'New Brunswick'), ('NS', 'Nova Scotia'), ('NU', 'Nunavut'), ('MB', 'Manitoba'), ('QC', 'Quebec'), ('YT', 'Yukon'), ('PE', 'Prince Edward Island'), ('NT', 'Northwest Territories'), ('SK', 'Saskatchewan'), ('NL', 'Newfoundland and Labrador'), ('ON', 'Ontario')], max_length=20, null=True, verbose_name='Province'),
        ),
    ]
