# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 04:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vjk', '0003_auto_20170329_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('service_provided', models.CharField(max_length=50)),
                ('primary_contact', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='vjk.Contacts')),
                ('secondary_contact', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='vjk.Contacts')),
            ],
        ),
    ]
