# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-11 04:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vjk', '0004_auto_20170709_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='student',
            name='aboriginal_group',
            field=models.CharField(blank=True, choices=[('First Nations', 'First Nations'), ('Inuit', 'Inuit'), ('Metis', 'Metis')], max_length=20, null=True, verbose_name='Aboriginal Group'),
        ),
        migrations.AddField(
            model_name='student',
            name='birth_date',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Birth date must be entered in form MM/DD/YYYY', regex='^\\d{2}/\\d{2}/\\d{4}')], verbose_name='Birth Date'),
        ),
        migrations.AddField(
            model_name='student',
            name='cell_phone',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+16045555555'.", regex='^\\+?1?\\d{10,12}$')], verbose_name='Cell Phone'),
        ),
        migrations.AddField(
            model_name='student',
            name='chaperone_fname',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='Chaperone First Name'),
        ),
        migrations.AddField(
            model_name='student',
            name='chaperone_lname',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='Chaperone Last Name'),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('O', 'Other'), ('F', 'Female'), ('M', 'Male')], max_length=10, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_email',
            field=models.EmailField(default='', max_length=254, verbose_name='Guard. Email'),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_fname',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='Guard. First Name'),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_lname',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='Guard. Last Name'),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_phone',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+16045555555'.", regex='^\\+?1?\\d{10,12}$')], verbose_name='Guard. Phone'),
        ),
        migrations.AddField(
            model_name='student',
            name='home_phone',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+16045555555'.", regex='^\\+?1?\\d{10,12}$')], verbose_name='Home Phone'),
        ),
        migrations.AddField(
            model_name='student',
            name='mentor',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='Mentor'),
        ),
        migrations.AddField(
            model_name='student',
            name='room_assignment',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='Room Assign.'),
        ),
        migrations.AddField(
            model_name='student',
            name='teacher_email',
            field=models.EmailField(default='', max_length=254, verbose_name='Teach. Email'),
        ),
        migrations.AddField(
            model_name='student',
            name='teacher_fname',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='Teach. First Name'),
        ),
        migrations.AddField(
            model_name='student',
            name='teacher_lname',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='Teach. Last Name'),
        ),
        migrations.AddField(
            model_name='student',
            name='teacher_phone',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+16045555555'.", regex='^\\+?1?\\d{10,12}$')], verbose_name='Teach. Phone'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='province',
            field=models.CharField(blank=True, choices=[('SK', 'Saskatchewan'), ('NL', 'Newfoundland and Labrador'), ('BC', 'British Columbia'), ('PE', 'Prince Edward Island'), ('NS', 'Nova Scotia'), ('MB', 'Manitoba'), ('NU', 'Nunavut'), ('NB', 'New Brunswick'), ('YT', 'Yukon'), ('NT', 'Northwest Territories'), ('QC', 'Quebec'), ('ON', 'Ontario'), ('AB', 'Alberta')], max_length=20, null=True, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='student',
            name='province',
            field=models.CharField(blank=True, choices=[('SK', 'Saskatchewan'), ('NL', 'Newfoundland and Labrador'), ('BC', 'British Columbia'), ('PE', 'Prince Edward Island'), ('NS', 'Nova Scotia'), ('MB', 'Manitoba'), ('NU', 'Nunavut'), ('NB', 'New Brunswick'), ('YT', 'Yukon'), ('NT', 'Northwest Territories'), ('QC', 'Quebec'), ('ON', 'Ontario'), ('AB', 'Alberta')], max_length=20, null=True, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='student',
            name='reference_province',
            field=models.CharField(blank=True, choices=[('SK', 'Saskatchewan'), ('NL', 'Newfoundland and Labrador'), ('BC', 'British Columbia'), ('PE', 'Prince Edward Island'), ('NS', 'Nova Scotia'), ('MB', 'Manitoba'), ('NU', 'Nunavut'), ('NB', 'New Brunswick'), ('YT', 'Yukon'), ('NT', 'Northwest Territories'), ('QC', 'Quebec'), ('ON', 'Ontario'), ('AB', 'Alberta')], max_length=20, null=True, verbose_name='Ref. Province'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='province',
            field=models.CharField(blank=True, choices=[('SK', 'Saskatchewan'), ('NL', 'Newfoundland and Labrador'), ('BC', 'British Columbia'), ('PE', 'Prince Edward Island'), ('NS', 'Nova Scotia'), ('MB', 'Manitoba'), ('NU', 'Nunavut'), ('NB', 'New Brunswick'), ('YT', 'Yukon'), ('NT', 'Northwest Territories'), ('QC', 'Quebec'), ('ON', 'Ontario'), ('AB', 'Alberta')], max_length=20, null=True, verbose_name='Province'),
        ),
    ]
