# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-03 17:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vjk', '0004_auto_20170703_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='province',
            field=models.CharField(blank=True, choices=[('NL', 'Newfoundland and Labrador'), ('NU', 'Nunavut'), ('YT', 'Yukon'), ('MB', 'Manitoba'), ('BC', 'British Columbia'), ('NS', 'Nova Scotia'), ('PE', 'Prince Edward Island'), ('QC', 'Quebec'), ('SK', 'Saskatchewan'), ('NT', 'Northwest Territories'), ('AB', 'Alberta'), ('NB', 'New Brunswick'), ('ON', 'Ontario')], max_length=20, null=True, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='service_provided',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Service Provided'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+16045555555'.", regex='^\\+?1?\\d{10,12}$')], verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='student',
            name='province',
            field=models.CharField(blank=True, choices=[('NL', 'Newfoundland and Labrador'), ('NU', 'Nunavut'), ('YT', 'Yukon'), ('MB', 'Manitoba'), ('BC', 'British Columbia'), ('NS', 'Nova Scotia'), ('PE', 'Prince Edward Island'), ('QC', 'Quebec'), ('SK', 'Saskatchewan'), ('NT', 'Northwest Territories'), ('AB', 'Alberta'), ('NB', 'New Brunswick'), ('ON', 'Ontario')], max_length=20, null=True, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='student',
            name='reference_email',
            field=models.EmailField(default='', max_length=254, verbose_name='Ref. E-mail'),
        ),
        migrations.AlterField(
            model_name='student',
            name='reference_province',
            field=models.CharField(blank=True, choices=[('NL', 'Newfoundland and Labrador'), ('NU', 'Nunavut'), ('YT', 'Yukon'), ('MB', 'Manitoba'), ('BC', 'British Columbia'), ('NS', 'Nova Scotia'), ('PE', 'Prince Edward Island'), ('QC', 'Quebec'), ('SK', 'Saskatchewan'), ('NT', 'Northwest Territories'), ('AB', 'Alberta'), ('NB', 'New Brunswick'), ('ON', 'Ontario')], max_length=20, null=True, verbose_name='Ref. Province'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='province',
            field=models.CharField(blank=True, choices=[('NL', 'Newfoundland and Labrador'), ('NU', 'Nunavut'), ('YT', 'Yukon'), ('MB', 'Manitoba'), ('BC', 'British Columbia'), ('NS', 'Nova Scotia'), ('PE', 'Prince Edward Island'), ('QC', 'Quebec'), ('SK', 'Saskatchewan'), ('NT', 'Northwest Territories'), ('AB', 'Alberta'), ('NB', 'New Brunswick'), ('ON', 'Ontario')], max_length=20, null=True, verbose_name='Province'),
        ),
    ]
