# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 02:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vjk', '0005_auto_20170328_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsors',
            name='primary_contact',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='vjk.Contacts'),
        ),
        migrations.AddField(
            model_name='sponsors',
            name='secondary_contact',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='vjk.Contacts'),
        ),
    ]
