# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vjk', '0004_sponsors'),
        ('vjk', '0007_auto_20170328_1916'),
    ]

    operations = [
    ]
